services:
  wildfly:
    build: .
    container_name: wildfly-finQueryPlus
    ports:
      - "8081:8080"
      - "9990:9990"
    environment:
      - JAVA_OPTS=-Djboss.bind.address.management=0.0.0.0 -Djboss.bind.address=0.0.0.0
    networks:
      - finQuery-net
    volumes:
      - ./deployment:/opt/jboss/wildfly/standalone/deployment

networks:
  finQuery-net:
    external: true

volumes:
  wildfly-data: